config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :models
  end

  namespace :admin do
    resources :slides
  end

  resources :slides

end

app/models/slide.rb
class Slide < ActiveRecord::Base
  validates :name, presence: true
  has_attached_file :pictures, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :pictures, content_type: /\Aimage\/.*\z/
end

app/controllers/admin/models_controller.rb
class Admin::ModelsController < ApplicationController
  before_action :set_model, only: [:show, :edit, :update, :destroy]

  # GET /admin/models
  # GET /admin/models.json
  def index
    @models = Model.all
  end

  # GET /admin/models/1
  # GET /admin/models/1.json
  def show
  end

  # GET /admin/models/new
  def new
    @model = Model.new
  end

  # GET /admin/models/1/edit
  def edit
  end

  # POST /admin/models
  # POST /admin/models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to [:admin, @model], notice: 'Model was successfully created.' }
        format.json { render action: 'show', status: :created, location: @model }
      else
        format.html { render action: 'new' }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/models/1
  # PATCH/PUT /admin/models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to [:admin, @model], notice: 'Model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/models/1
  # DELETE /admin/models/1.json
  def destroy
    @model.destroy
    respond_to do |format|
      format.html { redirect_to admin_models_url, notice: 'Model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_params
      params.require(:model).permit(:slides, :name, :desc_left, :desc_right, :pictures)
    end
end

app/controllers/admin/slides_controller.rb
class Admin::SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :edit, :update, :destroy]

  # GET /admin/slides
  # GET /admin/slides.json
  def index
    @slides = Slide.all
  end

  # GET /admin/slides/1
  # GET /admin/slides/1.json
  def show
  end

  # GET /admin/slides/new
  def new
    @slide = Slide.new
  end

  # GET /admin/slides/1/edit
  def edit
  end

  # POST /admin/slides
  # POST /admin/slides.json
  def create
    @slide = Slide.new(slide_params)

    respond_to do |format|
      if @slide.save
        format.html { redirect_to [:admin, @slide], notice: 'Slide was successfully created.' }
        format.json { render action: 'show', status: :created, location: @slide }
      else
        format.html { render action: 'new' }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/slides/1
  # PATCH/PUT /admin/slides/1.json
  def update
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to [:admin, @slide], notice: 'Slide was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/slides/1
  # DELETE /admin/slides/1.json
  def destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to admin_slides_url, notice: 'Slide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:name, :desc_left, :desc_right, :pictures)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  before_action :set_slide, only: [:show, :edit, :update, :destroy]

  # GET /slides
  # GET /slides.json
  def index
    @slides = Slide.all
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
  end

  # GET /slides/new
  def new
    @slide = Slide.new
  end

  # GET /slides/1/edit
  def edit
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(slide_params)

    respond_to do |format|
      if @slide.save
        format.html { redirect_to @slide, notice: 'Slide was successfully created.' }
        format.json { render :show, status: :created, location: @slide }
      else
        format.html { render :new }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slides/1
  # PATCH/PUT /slides/1.json
  def update
    respond_to do |format|
      if @slide.update(slide_params)
        format.html { redirect_to @slide, notice: 'Slide was successfully updated.' }
        format.json { render :show, status: :ok, location: @slide }
      else
        format.html { render :edit }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide.destroy
    respond_to do |format|
      format.html { redirect_to slides_url, notice: 'Slide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_slide
      @slide = Slide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def slide_params
      params.require(:slide).permit(:name, :desc_left, :desc_right,:pictures )
    end
end

app/helpers/admin/models_helper.rb
module Admin::ModelsHelper
end

app/helpers/admin/slides_helper.rb
module Admin::SlidesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/admin/models/_form.html.erb
<%= form_for([:admin, @model]) do |f| %>
  <% if @model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@model.errors.count, "error") %> prohibited this model from being saved:</h2>

      <ul>
      <% @model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :slides %><br>
    <%= f.text_field :slides %>
    </div>
  <div class="field">
      <%= f.label :name %><br>
    <%= f.text_field :name %>
    </div>
  <div class="field">
      <%= f.label :desc_left %><br>
    <%= f.text_area :desc_left %>
    </div>
  <div class="field">
      <%= f.label :desc_right %><br>
    <%= f.text_area :desc_right %>
    </div>
  <div class="field">
      <%= f.label :pictures %><br>
    <%= f.text_field :pictures %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/models/edit.html.erb
<h1>Editing model</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @model] %> |
<%= link_to 'Back', admin_models_path %>

app/views/admin/models/index.html.erb
<h1>Listing models</h1>

<table>
  <thead>
    <tr>
      <th>Slides</th>
      <th>Name</th>
      <th>Desc left</th>
      <th>Desc right</th>
      <th>Pictures</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @models.each do |model| %>
      <tr>
        <td><%= model.slides %></td>
        <td><%= model.name %></td>
        <td><%= model.desc_left %></td>
        <td><%= model.desc_right %></td>
        <td><%= model.pictures %></td>
        <td><%= link_to 'Show', [:admin, model] %></td>
        <td><%= link_to 'Edit', edit_admin_model_path(model) %></td>
        <td><%= link_to 'Destroy', [:admin, model], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Model', new_admin_model_path %>

app/views/admin/models/new.html.erb
<h1>New model</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_models_path %>

app/views/admin/models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Slides:</strong>
  <%= @model.slides %>
</p>

<p>
  <strong>Name:</strong>
  <%= @model.name %>
</p>

<p>
  <strong>Desc left:</strong>
  <%= @model.desc_left %>
</p>

<p>
  <strong>Desc right:</strong>
  <%= @model.desc_right %>
</p>

<p>
  <strong>Pictures:</strong>
  <%= @model.pictures %>
</p>

<%= link_to 'Edit', edit_admin_model_path(@model) %> |
<%= link_to 'Back', admin_models_path %>

app/views/admin/slides/_form.html.erb
<%= form_for([:admin, @slide]) do |f| %>
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% @slide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.label :name %><br>
    <%= f.text_field :name %>
    </div>
  <div class="field">
      <%= f.label :desc_left %><br>
    <%= f.text_area :desc_left %>
    </div>
  <div class="field">
      <%= f.label :desc_right %><br>
    <%= f.text_area :desc_right %>
    </div>
  <div class="field">
      <%= f.label :pictures %><br>
    <%= f.text_field :pictures %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/slides/edit.html.erb
<h1>Editing slide</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @slide] %> |
<%= link_to 'Back', admin_slides_path %>

app/views/admin/slides/index.html.erb
<h1>Listing slides</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc left</th>
      <th>Desc right</th>
      <th>Pictures</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @slides.each do |slide| %>
      <tr>
        <td><%= slide.name %></td>
        <td><%= slide.desc_left %></td>
        <td><%= slide.desc_right %></td>
        <td><%= image_tag slide.pictures.url(:thumb) %></td>
        <td><%= link_to 'Show', [:admin, slide] %></td>
        <td><%= link_to 'Edit', edit_admin_slide_path(slide) %></td>
        <td><%= link_to 'Destroy', [:admin, slide], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slide', new_admin_slide_path %>

app/views/admin/slides/new.html.erb
<h1>New slide</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_slides_path %>

app/views/admin/slides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @slide.name %>
</p>

<p>
  <strong>Desc left:</strong>
  <%= @slide.desc_left %>
</p>

<p>
  <strong>Desc right:</strong>
  <%= @slide.desc_right %>
</p>

<%= image_tag @slide.pictures.url(:thumb) %>
<%= link_to 'Edit', edit_admin_slide_path(@slide) %> |
<%= link_to 'Back', admin_slides_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sliders</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/slides/_form.html.erb
<%= form_for(@slide ,html: { multipart: true }) do  |f| %>
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% @slide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :testing%><br>
    <%= f.file_field :pictures %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :desc_left %><br>
    <%= f.text_area :desc_left %>
  </div>
  <div class="field">
    <%= f.label :desc_right %><br>
    <%= f.text_area :desc_right %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slides/edit.html.erb
<h1>Editing slide</h1>

<%= render 'form' %>

<%= link_to 'Show', @slide %> |
<%= link_to 'Back', slides_path %>

app/views/slides/index.html.erb
<h1>Listing slides</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>desc left</th>
      <th>desc right</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @slides.each do |slide| %>
      <tr>
        <td><%= slide.name %></td>
        <td><%= slide.desc_left %></td>
        <td><%= slide.desc_right %></td>
        <td><%= image_tag slide.pictures.url(:thumb) %></td>
        <td><%= link_to 'Show', slide %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Slide', new_slide_path %>

app/views/slides/new.html.erb
<h1>New slide</h1>

<%= render 'form' %>

<%= link_to 'Back', slides_path %>

app/views/slides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @slide.name %>
</p>

<p>
  <strong>desc left:</strong>
  <%= @slide.desc_left %>
</p>

<p>
  <strong>desc right:</strong>
  <%= @slide.desc_right %>
</p>
<%= image_tag @slide.pictures.url(:thumb) %>

<%= link_to 'Back', slides_path %>